controllers/class_room_controller.py
from flask import Blueprint
from flask import render_template, url_for, redirect, flash

from forms import EditClassRoomForm
from models import ClassRoom
from models import db

class_room_bp = Blueprint("class_room", __name__)


@class_room_bp.route("/")
def class_rooms_list():
    class_rooms = ClassRoom.query.all()
    return render_template("class_rooms.html", class_rooms=class_rooms, title="Class rooms")


@class_room_bp.route("/create", methods=["GET", "POST"])
def create():
    form = EditClassRoomForm()
    if form.validate_on_submit():
        class_room = ClassRoom()
        class_room.capacity = form.capacity.data
        db.session.add(class_room)
        db.session.commit()
        flash("Successed!")
        return redirect(url_for("class_room.class_rooms_list"))
    return render_template("form.html", form=form, title="Add new class room")


@class_room_bp.route("/edit/<_id>", methods=["post", "get"])
def edit(_id):
    class_room = ClassRoom.query.get_or_404(_id)
    form = EditClassRoomForm()

    if form.validate_on_submit():
        class_room.capacity = form.capacity.data
        db.session.add(class_room)
        db.session.commit()
        flash("Success!")
        return redirect(url_for("class_room.class_rooms_list"))
    else:
        form.capacity.data = class_room.capacity
    return render_template("form.html", form=form, title="Edit class room")


@class_room_bp.route("/delete/<_id>")
def delete(_id):
    del_classroom = ClassRoom.query.get_or_404(_id)
    db.session.delete(del_classroom)
    db.session.commit()

    flash("Deleted!")
    return redirect(url_for("class_room.class_rooms_list"))

controllers/home_controller.py
from flask import Blueprint, render_template

home_bp = Blueprint("home", __name__)


@home_bp.route("/")
@home_bp.route("/home")
def home():
    return render_template("home.html", title="Home")

templates/base.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}{{ title or 'VTP' }}{% endblock %}
{% block content %}
    <h2>{{ title }}</h2>
    {% if message %}
        <p>Message: {{ message }}</p>
    {% endif %}
{% endblock %}
{% block styles %}
    {{ super() }}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="//cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css">
{% endblock %}
{% block scripts %}
    {{ super() }}
    <link rel="stylesheet" href="//cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css">
    <script src="//cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    <script>
        $(document).ready(function () {
            $('table').DataTable();
        });
    </script>
{% endblock %}
{% block navbar %}
    <nav class="container navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{{ url_for("home.home") }}">VTP</a>
            </div>
            <ul class="nav navbar-nav">
                <li>
                    <a href="{{ url_for("class_room.class_rooms_list") }}">Phòng học</a>
                </li>

            </ul>
        </div>
    </nav>
{% endblock %}

templates/class_rooms.html
{% extends "base.html" %}
{% block content %}
    <h1 >Class rooms</h1>
    <a class="btn btn-success pull-right" href="{{ url_for('class_room.create') }}" style="margin-bottom: 20px"><i class="fa fa-plus"></i> Add new class room</a>

    <table class="table table-bordered">
        <thead>
        <tr>
            <th>UID</th>
            <th>Capacity</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        {% for class_room in class_rooms %}
            <tr>
                <td>{{ class_room.uid }}</td>
                <td>{{ class_room.capacity }}</td>
                <td>
                    <a href="{{ url_for('class_room.edit',_id=class_room.id) }}"
                       class="btn btn-primary"><i class="fa fa-pencil"></i> Edit</a>
                    <a href="{{ url_for('class_room.delete',_id=class_room.id) }}"
                       class="btn btn-danger"><i class="fa fa-trash"></i> Delete</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/form.html
{% extends "base.html" %}
{% block content %}
    {{ super() }}
    {{ wtf.quick_form(form) }}
{% endblock %}

templates/giao_vien.html
{%extends "base.html" %}
{%block content%}

<table class="table table-bordered">
    <div class="row">
        <div class="col md-12">
            <div class="jumbotron p-3">
                <h2>Manage <b>Teacher </b> <button type="button" class="btn btn-success float-right" data-toggle="modal" data-target="#mymodal">Add New Teachers</button></h2>

                {%with messages = get_flashed_messages()%}

                {%if messages%}
                
                {%for message in messages%}
                
                <div class="alert alert-success alert-dismissible" role="alert">

                    <button type="button" class="close" data-dismiss="alert" aria-label="close">
                        <span aria-hidden="true">x</span>
                    </button>

                    {{message}}
                    
                </div>
                
                {%endfor%}
                
                {%endif%}
                
                {%endwith%}
            </div>
            <thead>
                <tr>
                    <th>UID</th>
                    <th>Firstname</th>
                    <th>Lastname</th>
                    <th>Subject Taught</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody id="myTable">
                {%for teacher in teachers%}
                    <tr>
                        <td>{{teacher.uid}}</td>
                        <td>{{teacher.first_name}}</td>
                        <td>{{teacher.last_name}}</td>
                        <td>{{teacher.subject_taught}}</td>
                        <td>
                            <a href="/giao_vien/update/{{teacher.id}}" class="btn btn-outline-warning btn-xs" data-toggle="modal" data-target="#modaledit{{teacher.id}}">Edit</a>
                            <a href="/giao_vien/delete/{{teacher.id}}" class="btn btn-outline-danger btn-xs">Delete</a>
        
                        </td>
                    </tr>


                <div id="modaledit{{teacher.id}}" class="modal fade" role="dialog">

                    <div class="modal-dialog">
                        
                        <div class="modal-content">
                            
                            <div class="modal-header">
                
                                <h4 class="modal-title">Update Information</h4>
                            </div>
                            <div class="modal-body">
                
                                <form action="/giao_vien/update" method="POST">
                                    <div class="form-group">
                                        <label>First name:</label>
                                        <input type="hidden" name="id" value="{{teacher.id}}">

                                        <input type="text" class="form-control" name="first_name" value="{{teacher.first_name}}">
                                    </div>
                
                                    <div class="form-group">
                                        <label>Last name:</label>
                                        <input type="text" class="form-control" name="last_name" value="{{teacher.last_name}}">
                                    </div>
                
                                    <div class="form-group">
                                        <label>Subject taught:</label>
                                        <input type="datetime" class="form-control" name="subject_taught" value="{{teacher.date_of_birth}}">
                                    </div>
                
                                    <div class="form-group">
                                        <button class="btn btn-success" type="submit">Update</button>
                                        
                                    </div>
                
                                </form>
                
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                </div>
                {%endfor%}
            </tbody>


            <div id="mymodal" class="modal fade" role="dialog">

                <div class="modal-dialog">
                    
                    <div class="modal-content">
                        
                        <div class="modal-header">

                            <h4 class="modal-title">Add Teacher</h4>
                        </div>
                        <div class="modal-body">

                            <form action="/giao_vien/insert" method="POST">
                                <div class="form-group">
                                    <label>First name:</label>
                                    <input type="text" class="form-control" name="first_name" required="1">
                                </div>

                                <div class="form-group">
                                    <label>Last name:</label>
                                    <input type="text" class="form-control" name="last_name" required="1">
                                </div>

                                <div class="form-group">
                                    <label>Subject taught:</label>
                                    <input type="datetime" class="form-control" name="subject_taught" required="1">
                                </div>

                                <div class="form-group">
                                    <button class="btn btn-success" type="submit">Add teacher</button>
                                    
                                </div>

                            </form>

                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
</table>


{%endblock%}

templates/hoc_sinh.html
{%extends "base.html" %}
{%block content%}

<table class="table table-bordered">
    <div class="row">
        <div class="col md-12">
            <div class="jumbotron p-3">
                <h2>Manage <b>Student </b> <button type="button" class="btn btn-success float-right" data-toggle="modal" data-target="#mymodal">Add New Students</button></h2>

                {%with messages = get_flashed_messages()%}

                {%if messages%}
                
                {%for message in messages%}
                
                <div class="alert alert-success alert-dismissible" role="alert">

                    <button type="button" class="close" data-dismiss="alert" aria-label="close">
                        <span aria-hidden="true">x</span>
                    </button>

                    {{message}}
                    
                </div>
                
                {%endfor%}
                
                {%endif%}
                
                {%endwith%}
            </div>
            <thead>
                <tr>
                    <th style="display:none;">UID</th>
                    <th>Firstname</th>
                    <th>Lastname</th>
                    <th>Date of birth</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody id="myTable">
                {%for student in students%}
                    <tr>
                        <td style="display:none;">{{student.uid}}</td>
                        <td>{{student.first_name}}</td>
                        <td>{{student.last_name}}</td>
                        <td>{{student.date_of_birth}}</td>
                        <td>
                            <a href="" class="btn btn-outline-warning btn-xs" data-toggle="modal" data-target="#modaledit">Edit</a>
                            <a href="" class="btn btn-outline-danger btn-xs" onclick="confirm('Are you sure to Delete ?')">Delete</a>
        
                        </td>
                    </tr>
                {%endfor%}
            </tbody>

            <div id="modaledit" class="modal fade" role="dialog">

                <div class="modal-dialog">
                    
                    <div class="modal-content">
                        
                        <div class="modal-header">
            
                            <h4 class="modal-title">Update Information</h4>
                        </div>
                        <div class="modal-body">
            
                            <form action="" method="POST">
                                <div class="form-group">
                                    <label>First name:</label>
                                    <input type="hidden" name="id" value="id">

                                    <input type="text" class="form-control" name="first_name" required="1">
                                </div>
            
                                <div class="form-group">
                                    <label>Last name:</label>
                                    <input type="text" class="form-control" name="last_name" required="1">
                                </div>
            
                                <div class="form-group">
                                    <label>Date of birth:</label>
                                    <input type="datetime" class="form-control" name="date_of_birth" required="1">
                                </div>
            
                                <div class="form-group">
                                    <button class="btn btn-success" type="submit">Update</button>
                                    
                                </div>
            
                            </form>
            
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>


            <div id="mymodal" class="modal fade" role="dialog">

                <div class="modal-dialog">
                    
                    <div class="modal-content">
                        
                        <div class="modal-header">

                            <h4 class="modal-title">Add Student</h4>
                        </div>
                        <div class="modal-body">

                            <form action="/insert" method="POST">
                                <div class="form-group">
                                    <label>First name:</label>
                                    <input type="text" class="form-control" name="first_name" required="1">
                                </div>

                                <div class="form-group">
                                    <label>Last name:</label>
                                    <input type="text" class="form-control" name="last_name" required="1">
                                </div>

                                <div class="form-group">
                                    <label>Date of birth:</label>
                                    <input type="datetime" class="form-control" name="date_of_birth" required="1">
                                </div>

                                <div class="form-group">
                                    <button class="btn btn-success" type="submit">Add student</button>
                                    
                                </div>

                            </form>

                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
</table>


{%endblock%}

templates/home.html
{%extends "base.html" %}
{%block content%}
<h1>Hello world</h1>
{%endblock%}

templates/mon_hoc.html
{%extends "base.html" %}
{%block content%}

<table class="table table-bordered">
    <div class="row">
        <div class="col md-12">
            <div class="jumbotron p-3">
                <h2>Manage <b>Subject </b> <button type="button" class="btn btn-success float-right" data-toggle="modal" data-target="#mymodal">Add New Subjects</button></h2>

                {%with messages = get_flashed_messages()%}

                {%if messages%}
                
                {%for message in messages%}
                
                <div class="alert alert-success alert-dismissible" role="alert">

                    <button type="button" class="close" data-dismiss="alert" aria-label="close">
                        <span aria-hidden="true">x</span>
                    </button>

                    {{message}}
                    
                </div>
                
                {%endfor%}
                
                {%endif%}
                
                {%endwith%}
            </div>
            <thead>
                <tr>
                    <th>UID</th>
                    <th>Name</th>
                    <th>Capacity</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody id="myTable">
                {%for subject in subjects%}
                    <tr>
                        <td>{{subject.uid}}</td>
                        <td>{{subject.name}}</td>
                        <td>{{subject.capacity}}</td>
                        <td>
                            <a href="/mon_hoc/update/{{subject.id}}" class="btn btn-outline-warning btn-xs" data-toggle="modal" data-target="#modaledit{{subject.id}}">Edit</a>
                            <a href="/mon_hoc/delete/{{subject.id}}" class="btn btn-outline-danger btn-xs">Delete</a>
        
                        </td>
                    </tr>


                <div id="modaledit{{subject.id}}" class="modal fade" role="dialog">

                    <div class="modal-dialog">
                        
                        <div class="modal-content">
                            
                            <div class="modal-header">
                
                                <h4 class="modal-title">Update Information</h4>
                            </div>
                            <div class="modal-body">
                
                                <form action="/mon_hoc/update" method="POST">
                                    <div class="form-group">
                                        <label>Name:</label>
                                        <input type="hidden" name="id" value="{{subject.id}}">

                                        <input type="text" class="form-control" name="name" value="{{subject.capacity}}">
                                    </div>

                                    <div class="form-group">
                                        <label>Capacity:</label>
                                        <input type="hidden" name="id" value="{{subject.id}}">

                                        <input type="text" class="form-control" name="capacity" value="{{subject.capacity}}">
                                    </div>
                
                                    <div class="form-group">
                                        <button class="btn btn-success" type="submit">Update</button>
                                        
                                    </div>
                
                                </form>
                
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                </div>
                {%endfor%}
            </tbody>


            <div id="mymodal" class="modal fade" role="dialog">

                <div class="modal-dialog">
                    
                    <div class="modal-content">
                        
                        <div class="modal-header">

                            <h4 class="modal-title">Add Subject</h4>
                        </div>
                        <div class="modal-body">

                            <form action="/mon_hoc/insert" method="POST">
                                <div class="form-group">
                                    <label>Name:</label>
                                    <input type="text" class="form-control" name="name" required="1">
                                </div>
                                
                                <div class="form-group">
                                    <label>Capacity:</label>
                                    <input type="text" class="form-control" name="capacity" required="1">
                                </div>

                                <div class="form-group">
                                    <button class="btn btn-success" type="submit">Add subject</button>
                                    
                                </div>

                            </form>

                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
</table>


{%endblock%}